ignores:
  - depcheck
  - declapract
  - declapract-typescript-ehmpathy
  - '@commitlint/config-conventional'
  - husky
  - '@oclif/plugin-help'
  - oclif
  - tsx # used in `./bin/run
  - rhachet
  - "@tsconfig/node20"
  - "@tsconfig/strictest"
  - "@biomejs/biome"
  - esbuild-register
  - "@swc/core"
  - "@swc/jest"
  - type-fns # used transitively
  - "@tsconfig/node-lts-strictest" # likely used in other configs
  - core-js # polyfill
  - test-fns # test utilities
  - ts-jest # kept for compatibility
