name: ci_on_commit

on:
  push:
    branches: # run for any branch
      - '**'
    tags-ignore: # but not for releases, as deploy_on_tag will trigger for it
      - v*

jobs:
  install:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v1

      - name: install
        run: npm install

      - name: cache node modules
        uses: actions/cache@v1
        with:
          path: node_modules
          key: ${{ runner.os }}-node-${{ github.sha }}

  # run tests in parallel
  test_types:
    runs-on: ubuntu-latest
    needs: [install]
    steps:
      - name: checkout
        uses: actions/checkout@v1

      - name: grab node_modules from cache
        uses: actions/cache@v1
        with:
          path: node_modules
          key: ${{ runner.os }}-node-${{ github.sha }}

      - name: test:types
        run: npm run test:types

  test_format:
    runs-on: ubuntu-latest
    needs: [install]
    steps:
      - name: checkout
        uses: actions/checkout@v1

      - name: grab node_modules from cache
        uses: actions/cache@v1
        with:
          path: node_modules
          key: ${{ runner.os }}-node-${{ github.sha }}

      - name: test:types
        run: npm run test:format

  test_lint:
    runs-on: ubuntu-latest
    needs: [install]
    steps:
      - name: checkout
        uses: actions/checkout@v1

      - name: grab node_modules from cache
        uses: actions/cache@v1
        with:
          path: node_modules
          key: ${{ runner.os }}-node-${{ github.sha }}

      - name: test:lint
        run: npm run test:lint

  test_unit:
    runs-on: ubuntu-latest
    needs: [install]
    steps:
      - name: checkout
        uses: actions/checkout@v1

      - name: grab node_modules from cache
        uses: actions/cache@v1
        with:
          path: node_modules
          key: ${{ runner.os }}-node-${{ github.sha }}

      - name: test:unit
        run: npm run test:unit

  test_integration:
    runs-on: ubuntu-latest
    needs: [install]
    steps:
      - name: checkout
        uses: actions/checkout@v1

      - name: grab node_modules from cache
        uses: actions/cache@v1
        with:
          path: node_modules
          key: ${{ runner.os }}-node-${{ github.sha }}

      - name: provision:integration-test-db
        run: npm run provision:integration-test-db

      - name: test:integration
        run: npm run test:integration
