name: deploy_on_tag

on:
  push:
    tags:
      - v*

jobs:
  test_and_deploy:
    runs-on: ubuntu-20.04
    steps:
      - name: checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0 # we need all commits to test:commits

      - name: read nvmrc
        id: nvmrc
        run: echo ::set-output name=NODE_VERSION::$(cat .nvmrc)

      - name: setup node
        uses: actions/setup-node@v2
        with:
          node-version: ${{ steps.nvmrc.outputs.NODE_VERSION }}
          registry-url: 'https://registry.npmjs.org'
          cache: 'npm'

      - name: install
        run: npm ci

      - name: tests
        run: npm run test
        env:
          FORCE_COLOR: true # ensure colors are saved in jest snapshots, to be consistent with local development

      - name: publish
        run: npm publish
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
