language: mysql
dialect: 5.7
connection: ./connection.config.js
definitions:
  - type: change
    id: first_change
    path: ./first_change.sql
  - ./definitions/changes.yml
  - ./definitions/resources.yml
  - ./empty_file.yml # e.g., placeholder files
